### ISSUE TITLE
Problem with config

### ISSUE THREAD

**Issue by uxandai** [mjvotaw/plex-sub-downloader#1]
Great Idea! But...

plex_sub_downloader --config /Volumes/External/Subtitles/conf/plex-sub-downloader.json start-webhook --debug

```2022-09-12 19:09:37:plex_sub_downloader:DEBUG - cmdline arguments:
2022-09-12 19:09:37:plex_sub_downloader:DEBUG - Namespace(config='/Volumes/External/Subtitles/conf/plex-sub-downloader.json', debug=True, command=['start-webhook'])
2022-09-12 19:09:37:plex_sub_downloader:DEBUG - Config params:
2022-09-12 19:09:37:plex_sub_downloader:DEBUG - {'plex_base_url': 'http://localhost:32400', 'plex_auth_token': 'xxxxxxxx-hidden', 'subliminal': {'languages': ['eng']}, 'webhook_host': '0.0.0.0', 'webhook_port': 5002}
2022-09-12 19:09:37:PlexSubDownloader:INFO - Configuring PlexSubDownloader
Traceback (most recent call last):
  File "/opt/homebrew/bin/plex_sub_downloader", line 8, in <module>
    sys.exit(plex_sub_downloader.main())
  File "/opt/homebrew/lib/python3.10/site-packages/plex_sub_downloader/plex_sub_downloader.py", line 76, in main
    if psd.configure(config) == False:
  File "/opt/homebrew/lib/python3.10/site-packages/plex_sub_downloader/PlexSubDownloader.py", line 30, in configure
    self.sub = SubliminalHelper(languages=config.get('languages', None), 
  File "/opt/homebrew/lib/python3.10/site-packages/plex_sub_downloader/subliminalHelper.py", line 24, in __init__
    self.languages = set([subliminal.core.Language(lang) for lang in languages])
TypeError: 'NoneType' object is not iterable
```

**Comment by uxandai** [comment]
ok should be
```
        "languages": [
            "pol"
        ]
```
instead of    
```
    "subliminal": {
        "languages": [
            "pol"
        ]
    },
```
Testing.
PS If you need GUI contact me ;)

**Comment by ghost** [comment]
Oof, thanks for catching that. I forgot to update the readme at some point.
