### ISSUE TITLE
ERROR in app: Exception on /webhook [POST]

### ISSUE THREAD

**Issue by sasagr** [mjvotaw/plex-sub-downloader#3]
The subtitle was downloaded and added to the metadata but I saw the following error in debug.
How to fix it?

```
2022-11-02 13:20:20:PlexSubDownloader:DEBUG - handleWebhookEvent
2022-11-02 13:20:20:PlexSubDownloader:DEBUG - Event type: library.new
2022-11-02 13:20:20:PlexSubDownloader:INFO - Handling library.new event
2022-11-02 13:20:20:PlexSubDownloader:INFO - Title: Empathy Bonus, type: episode, section: TV Shows
2022-11-02 13:20:21:PlexSubDownloader:INFO - Found 1 videos missing subtitles
2022-11-02 13:20:21:PlexSubDownloader:INFO - ['Empathy Bonus, /library/metadata/9530']
2022-11-02 13:20:21:PlexSubDownloader:INFO - Downloading subtitles for 1 videos
2022-11-02 13:20:21:PlexSubDownloader:INFO - ['Empathy Bonus']
2022-11-02 13:20:23:PlexSubDownloader:INFO - Saving subtitles to Plex metadata
2022-11-02 13:20:23:PlexSubDownloader:INFO - found 1 for video /mnt/REDEB/shows/the.peripheral.s01e02.hdr.2160p.web.h265-glhf.mkv/the.peripheral.s01e02.hdr.2160p.web.h265-glhf.mkv
2022-11-02 13:20:23:subliminalHelper:DEBUG - Saving subtitle file to /tmp
2022-11-02 13:20:23:PlexSubDownloader:DEBUG - Uploading subtitles '/tmp/the.peripheral.s01e02.hdr.2160p.web.h265-glhf.en.srt' to video Empathy Bonus /library/metadata/9530
[2022-11-02 13:20:23,443] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/.local/lib/python3.7/site-packages/plex_sub_downloader/plex_sub_downloader.py", line 27, in respond
    psd.handleWebhookEvent(event)
  File "/home/pi/.local/lib/python3.7/site-packages/plex_sub_downloader/PlexSubDownloader.py", line 50, in handleWebhookEvent
    self.handleLibraryNewEvent(event)
  File "/home/pi/.local/lib/python3.7/site-packages/plex_sub_downloader/PlexSubDownloader.py", line 69, in handleLibraryNewEvent
    self.uploadSubtitlesToMetadata(missingVideos, subtitles)
  File "/home/pi/.local/lib/python3.7/site-packages/plex_sub_downloader/PlexSubDownloader.py", line 168, in uploadSubtitlesToMetadata
    mediaPart.setDefaultSubtitleStream(originalDefault)
  File "/home/pi/.local/lib/python3.7/site-packages/plexapi/media.py", line 210, in setDefaultSubtitleStream
    self._server.query(key, method=self._server._session.put)
  File "/home/pi/.local/lib/python3.7/site-packages/plexapi/server.py", line 707, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (400) bad_request; http://127.0.0.1:32400/library/parts/19604?subtitleStreamID=69849&allParts=1 <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
192.168.1.18 - - [02/Nov/2022 13:20:23] "POST /webhook HTTP/1.1" 500 -
```

**Comment by ghost** [comment]
It looks like the error is coming from the application trying to set the default subtitle back to it's original value after uploading the new subtitles (Plex automatically sets the newly uploaded subtitles as default, and the application is trying to undo that). Though, thinking about it now, that may actually be the preferred functionality for people.

I'll have to test this and see if I can recreate the problem.
